title: I have an error in the Console
hero_image: images/banner.png
description: I have an error in the Console
version: 4
listed: false
copyedit: false
last_tested: "2021-11-23"
steps:
  - 
    title: I have an error in the Console
